# Generated by Django 4.2.3 on 2024-02-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0017_alter_perfil_estado_alter_perfil_estado_trabalho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.colunas')),
            ],
        ),
        migrations.CreateModel(
            name='Quadros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('usuario', models.ManyToManyField(to='usuario.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='colunas',
            name='quadro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.quadros'),
        ),
    ]
