# Generated by Django 4.2.3 on 2024-02-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colunas',
            options={'verbose_name_plural': 'Colunas'},
        ),
        migrations.AlterModelOptions(
            name='quadros',
            options={'verbose_name_plural': 'Quadros'},
        ),
        migrations.AlterModelOptions(
            name='tarefas',
            options={'verbose_name_plural': 'Tarefas'},
        ),
    ]
