version: '3.9'

volumes:
  intranet_data:
    name: intranet_data
    # persists postgres data against docker-compose down

services:
  backend:
    build:
        # platform: linux/x86_64
        context: .
        args:
          service_name: backend
    image: backend
    container_name: backend
    entrypoint: /entrypoint.sh
    command: "python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - database
    ports:
      - "8001:8001"
    volumes:
      - .:/code # more aggressive copy than Dockerfile. This puts all the scripts on the container for local dev
    networks:
      - intranet-network

  database:
    # set "database" as app's DB_HOST.
    image: postgres:13
    container_name: backend-db
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-p"
      - "6000"
    environment:
      - DATABASE_HOST=database
      - POSTGRES_USER=flavio
      - POSTGRES_PASSWORD=314628
      - POSTGRES_DB=intranet_innovatore
    ports:
      - "6000:6000"
    volumes:
      - intranet_data:/var/lib/postgresql/data
    networks:
      - intranet-network

networks:
  intranet-network:
    name: intranet-network