version: '3.9'

volumes:
  intranet_data:
    name: intranet_data
    # persists postgres data against docker-compose down

  cache:
    driver: local
    name: intranet_redis


services:
  backend:
    build:
        # platform: linux/x86_64
        context: .
        args:
          service_name: backend
    image: backend
    container_name: backend
    # entrypoint: /entrypoint.sh
    command: gunicorn intranet_innovatore.wsgi:application --bind 0.0.0.0:8001
    depends_on:
      - database
      - redis
    expose:
      - 8001
    networks:
      - intranet-network

  database:
    # set "database" as app's DB_HOST.
    image: postgres:13
    container_name: backend-db
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-p"
      - "6000"
    environment:
      - DATABASE_HOST=database
      - POSTGRES_USER=flavio
      - POSTGRES_PASSWORD=314628
      - POSTGRES_DB=intranet_innovatore
    ports:
      - "6000:6000"
    volumes:
      - intranet_data:/var/lib/postgresql/data
    networks:
      - intranet-network
    
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6380'
    command: redis-server --port 6380
    volumes: 
      - cache:/data
    networks:
      - intranet-network
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/intranet_innovatore/statics
    depends_on:
      - backend
    networks:
      - intranet-network

networks:
  intranet-network:
    name: intranet-network
