version: '3.9'

volumes:
  intranet_data:
    name: intranet_data
    # persists postgres data against docker-compose down

  cache:
    driver: local
    name: intranet_redis

  static_volume:
    name: arquivos_estaticos

  media_volume:
    name: arquivos_de_media


services:
  backend:
    build:
        # platform: linux/x86_64
        context: .
        args:
          service_name: backend
    image: backend
    container_name: backend
    volumes:
      - static_volume:/usr/src/app/intranet_innovatore/static
      - media_volume:/usr/src/app/intranet_innovatore/media
    environment:
      - SECRET_KEY=${SECRET_KEY}
    entrypoint: /usr/src/app/entrypoint.sh
    command: gunicorn intranet_innovatore.wsgi:application --bind 0.0.0.0:8001
    depends_on:
      - database
      - redis
      - daphne
    expose:
      - 8001
    networks:
      - intranet-network

  daphne:
    build:
      # platform: linux/x86_64
      context: .
      args:
        service_name: daphne
    command: daphne -b 0.0.0.0 -p 8070 intranet_innovatore.asgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=intranet_innovatore.settings
    expose: 
      - 8070
    networks:
      - intranet-network
    depends_on:
      - database
      - redis
    
  database:
    # set "database" as app's DB_HOST.
    image: postgres:13
    container_name: backend-db
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-p"
      - "6000"
    environment:
      - DATABASE_HOST=database
      - POSTGRES_USER=flavio
      - POSTGRES_PASSWORD=314628
      - POSTGRES_DB=intranet_innovatore
    ports:
      - "6000:6000"
    volumes:
      - intranet_data:/var/lib/postgresql/data
    networks:
      - intranet-network
    
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6380'
    command: redis-server --port 6380
    volumes: 
      - cache:/data
    networks:
      - intranet-network
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/intranet_innovatore/static
      - media_volume:/usr/src/app/intranet_innovatore/media
    depends_on:
      - backend
    networks:
      - intranet-network

networks:
  intranet-network:
    name: intranet-network
