# Generated by Django 4.2.3 on 2023-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="public",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
