# Generated by Django 4.2.3 on 2023-12-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendario", "0002_alter_events_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={"verbose_name_plural": "Eventos"},
        ),
        migrations.AddField(
            model_name="events",
            name="allDay",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
