# Generated by Django 4.2.3 on 2024-03-12 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_alter_events_options_events_allday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
