# Generated by Django 4.2.3 on 2023-09-27 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Qualidade',
            },
        ),
    ]
