# Generated by Django 4.2.3 on 2023-09-29 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Comercial',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Departamento Pessoal',
            },
        ),
        migrations.CreateModel(
            name='Engenharia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Engenharia',
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Financeiro',
            },
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Fiscal',
            },
        ),
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Jurídico',
            },
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Logística',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Marketing',
            },
        ),
        migrations.CreateModel(
            name='MeioAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Meio Ambiente',
            },
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='PMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'P.M.O.',
            },
        ),
        migrations.CreateModel(
            name='RecursosHumanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Recursos Humanos',
            },
        ),
        migrations.CreateModel(
            name='SegurancaDoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Segurança do Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Sistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='Suprimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Suprimentos',
            },
        ),
        migrations.CreateModel(
            name='TI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'T.I.',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(blank=True, upload_to='qualidade/')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
