# Generated by Django 4.2.3 on 2024-03-12 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_alter_comercial_doc_alter_controladoria_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(upload_to='documentos_gerais/')),
            ],
            options={
                'verbose_name_plural': 'Documentos Gerais',
            },
        ),
    ]
