# Generated by Django 4.2.3 on 2024-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_documentosgerais'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='controladoria',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='departamentopessoal',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='documentosgerais',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='engenharia',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fiscal',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='juridico',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='logistica',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='marketing',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meioambiente',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pmo',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='qualidade',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='recursoshumanos',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='segurancadotrabalho',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sistemas',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='suprimentos',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ti',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendas',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
    ]
