# Generated by Django 4.2.3 on 2024-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_comercial_codigo_controladoria_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercial',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comercial',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='controladoria',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='controladoria',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='departamentopessoal',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='departamentopessoal',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentosgerais',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentosgerais',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='engenharia',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='engenharia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='juridico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='logistica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meioambiente',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meioambiente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orcamentos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pmo',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pmo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recursoshumanos',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recursoshumanos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='segurancadotrabalho',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='segurancadotrabalho',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemas',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sistemas',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suprimentos',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='suprimentos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ti',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ti',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='codigo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
