# Generated by Django 4.2.3 on 2024-03-26 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_alter_comercial_codigo_alter_comercial_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=150)),
                ('nome', models.CharField(max_length=150)),
                ('modificado', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(choices=[('PDF', 'pdf'), ('TXT', 'txt'), ('XLS', 'xls'), ('DOC', 'doc'), ('PPT', 'ppt')], default='PDF', max_length=150)),
                ('doc', models.FileField(upload_to='diretoria/')),
            ],
            options={
                'verbose_name_plural': 'Diretoria',
            },
        ),
        migrations.DeleteModel(
            name='DepartamentoPessoal',
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
    ]
