# Generated by Django 4.2.3 on 2023-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloco",
            name="titulo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
