# Generated by Django 4.2.3 on 2023-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0002_alter_bloco_titulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticia",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
