# Generated by Django 4.2.3 on 2023-12-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0003_noticia_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloco",
            old_name="imagem",
            new_name="imagem_bloco",
        ),
    ]
