# Generated by Django 4.2.3 on 2023-12-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0004_rename_imagem_bloco_imagem_bloco"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloco",
            old_name="paragrafo",
            new_name="paragrafo_bloco",
        ),
        migrations.RenameField(
            model_name="bloco",
            old_name="titulo",
            new_name="titulo_bloco",
        ),
    ]
