# Generated by Django 4.2.3 on 2023-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0005_rename_paragrafo_bloco_paragrafo_bloco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloco",
            name="imagem_bloco",
            field=models.ImageField(
                blank=True, null=True, upload_to="informativos/imagem_bloco"
            ),
        ),
    ]
