# Generated by Django 4.2.3 on 2023-12-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0006_alter_bloco_imagem_bloco"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloco",
            name="noticia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="informativos.noticia",
            ),
        ),
    ]
