# Generated by Django 4.2.3 on 2024-01-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0007_bloco_noticia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunicado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255, null=True)),
                ("paragrafo", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
