# Generated by Django 4.2.3 on 2024-01-03 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0008_comunicado"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicado",
            name="publicado_em",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
