# Generated by Django 4.2.3 on 2024-01-04 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informativos", "0009_comunicado_publicado_em"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quadro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255, null=True)),
                ("paragrafo", models.TextField(blank=True, null=True)),
                ("publicado_em", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
