# Generated by Django 4.2.3 on 2024-01-15 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_alter_perfil_estado_alter_perfil_estado_trabalho_and_more'),
        ('informativos', '0010_quadro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario_noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informativos.noticia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.perfil')),
            ],
        ),
    ]
