# Generated by Django 4.2.3 on 2023-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('horas', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
