# Generated by Django 4.2.3 on 2023-10-13 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
