# Generated by Django 4.2.3 on 2023-10-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name_plural': 'Cursos'},
        ),
    ]
