# Generated by Django 4.2.3 on 2023-08-24 17:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_certificado", models.CharField(max_length=30, null=True)),
                ("organizacao", models.CharField(max_length=30, null=True)),
                (
                    "inicio_curso",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                (
                    "termino_curso",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                ("horas", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experiencia", models.TextField(blank=True, null=True)),
                ("empresa", models.CharField(max_length=30, null=True)),
                ("localidade", models.CharField(max_length=30, null=True)),
                ("forma_trabalho", models.CharField(max_length=30, null=True)),
                (
                    "inicio_trabalho",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                (
                    "termino_trabalho",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                ("descricao_trabalho", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao", models.CharField(max_length=30, null=True)),
                ("diploma", models.CharField(max_length=30, null=True)),
                ("area_estudo", models.CharField(max_length=30, null=True)),
                (
                    "inicio_faculdade",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                (
                    "termino_faculdade",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                ("descricao_faculdade", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Habilidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habilidades", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hobbies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hobbies", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, height_field=40, upload_to="fotos", width_field=40
                    ),
                ),
                ("fundo", models.ImageField(blank=True, upload_to="fundos")),
                ("nome", models.CharField(max_length=20, null=True)),
                ("sobrenome", models.CharField(max_length=50, null=True)),
                (
                    "nascimento",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("masculino", "MASCILINO"), ("feminino", "FEMININO")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=50, null=True)),
                ("contato", models.CharField(max_length=16)),
                ("cpf", models.CharField(max_length=14, null=True)),
                ("rg", models.CharField(max_length=25, null=True)),
                ("endereco", models.CharField(max_length=50, null=True)),
                ("bairro", models.CharField(max_length=30, null=True)),
                ("cidade", models.CharField(max_length=50, null=True)),
                ("estado", models.CharField(max_length=30, null=True)),
                ("numero", models.CharField(max_length=15, null=True)),
                ("complemento", models.CharField(blank=True, max_length=30, null=True)),
                ("cargo_inicial", models.CharField(max_length=30, null=True)),
                ("cargo", models.CharField(max_length=30, null=True)),
                ("setor", models.CharField(max_length=30, null=True)),
                ("cidade_trabalho", models.CharField(max_length=30, null=True)),
                ("estado_trabalho", models.CharField(max_length=30, null=True)),
                (
                    "data_inicio",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                (
                    "data_mudanca",
                    models.DateField(default=datetime.datetime.now, null=True),
                ),
                ("email_empresa", models.EmailField(max_length=30, null=True)),
                ("telefone", models.CharField(max_length=30, null=True)),
                ("obra_trabalho", models.CharField(max_length=30, null=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
