# Generated by Django 4.2.3 on 2023-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_sobre_remove_experiencia_experiencia_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sobre",
        ),
        migrations.AddField(
            model_name="perfil",
            name="texto_experiencia",
            field=models.TextField(blank=True, null=True),
        ),
    ]
