# Generated by Django 4.2.3 on 2023-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0005_cursos_perfil_formacao_perfil_habilidades_perfil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursos",
            name="inicio_curso",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cursos",
            name="termino_curso",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="inicio_trabalho",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="termino_trabalho",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="inicio_faculdade",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="termino_faculdade",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="contato",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="data_inicio",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="data_mudanca",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="nascimento",
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
