# Generated by Django 4.2.3 on 2023-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0007_cursos_descricao_curso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cursos",
            name="nome_certificado",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cursos",
            name="organizacao",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="empresa",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="forma_trabalho",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="localidade",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="area_estudo",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="diploma",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="instituicao",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="habilidades",
            name="habilidades",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="hobbies",
            name="hobbies",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="bairro",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="cargo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="cargo_inicial",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="cidade_trabalho",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email_empresa",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Acre", "AC"),
                    ("Alagoas", "AL"),
                    ("Amapá", "AP"),
                    ("Amazonas", "AM"),
                    ("Bahia", "BA"),
                    ("Ceará", "CE"),
                    ("Distrito Federal", "DF"),
                    ("Espírito Santo", "ES"),
                    ("Goiás", "GO"),
                    ("Maranhão", "MA"),
                    ("Mato Grosso", "MT"),
                    ("Mato Grosso do Sul", "MS"),
                    ("Minas Gerais", "MG"),
                    ("Pará", "PA"),
                    ("Paraíba", "PB"),
                    ("Paraná", "PR"),
                    ("Pernambuco", "PE"),
                    ("Piauí", "PI"),
                    ("Rio de Janeiro", "RJ"),
                    ("Rio Grande do Norte", "RN"),
                    ("Rio Grande do Sul", "RS"),
                    ("Rondônia", "RO"),
                    ("Roraima", "RR"),
                    ("Santa Catarina", "SC"),
                    ("São Paulo", "SP"),
                    ("Sergipe", "SE"),
                    ("Tocantins", "TO"),
                ],
                default="AC",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="nome",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="obra_trabalho",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="setor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
