# Generated by Django 4.2.3 on 2023-09-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0008_alter_cursos_nome_certificado_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cursos",
            options={"verbose_name_plural": "Cursos"},
        ),
        migrations.AlterModelOptions(
            name="experiencia",
            options={"verbose_name_plural": "Experiências"},
        ),
        migrations.AlterModelOptions(
            name="formacao",
            options={"verbose_name_plural": "Formações"},
        ),
        migrations.AlterModelOptions(
            name="habilidades",
            options={"verbose_name_plural": "Habilidades"},
        ),
        migrations.AlterModelOptions(
            name="hobbies",
            options={"verbose_name_plural": "Hobbies"},
        ),
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name_plural": "Perfis"},
        ),
        migrations.AddField(
            model_name="experiencia",
            name="cargo_empresa",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(blank=True, upload_to="fotos/"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="fundo",
            field=models.ImageField(blank=True, upload_to="fundos/"),
        ),
    ]
