# Generated by Django 4.2.3 on 2023-09-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0009_alter_cursos_options_alter_experiencia_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formacao",
            name="area_estudo",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="diploma",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
