# Generated by Django 4.2.3 on 2023-08-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0002_alter_qualidade_doc"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualidade",
            options={"verbose_name_plural": "Qualidade"},
        ),
        migrations.AddField(
            model_name="qualidade",
            name="subpasta",
            field=models.CharField(
                choices=[("finaceiro", "/financeiro/"), ("vendas", "/vendas/")],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="qualidade",
            name="doc",
            field=models.FileField(
                blank=True,
                upload_to="docs/qualidade/<django.db.models.fields.CharField>",
            ),
        ),
    ]
